### PR TITLE
Added enlarging effect

### PR DESCRIPTION
**Pull request by mohityadav0903**

### CODE REVIEW

**Comment by mohityadav0903** [comment]
@ishqDehlvi Please review my PR #5

**Comment by ishqDehlvi** [comment]
> @ishqDehlvi Please review my PR #5 

Accepted.......... Can you make the mobile navbar too..

**Comment by mohityadav0903** [comment]
@ishqDehlvi ok i will work on it.

**Comment by ishqDehlvi** [comment]
@mohityadav0903  okie thanks

**Pull request merged**
